# Fixes Logisim
wmname compiz

# Sets up compositor
picom &

unclutter &

xfce4-screensaver &

xfce4-power-manager &

xrandr --output HDMI-1 --mode 1920x1080 --rate 60

/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Sets up dwmblocks
dwmblocks &

# Sets up background image
./.fehbg &

exec dwm
