unclutter &

xfce4-screensaver &

xfce4-notifyd & 

xfce4-power-manager &

xrandr --output HDMI-1 --mode 1920x1080 --rate 60

# Fixes Logisim
wmname compiz

# Sets up compositor
picom &

# Sets up dwmblocks
dwmblocks &

# Sets up background image
feh --bg-scale ~/Images/dedsec.jpg &
exec dwm
