" NICUP14's vim configuration file

" Theme
if !has('nvim')
    colorscheme dracula
endif

" General
set nocompatible
syntax on
filetype plugin indent on

" UI
set number
set wrap
set background=dark

" Searching
set ignorecase
set incsearch
set showmatch
set nohlsearch

" Indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
" set autoindent

" Disable folding
set nofoldenable
set foldmethod=manual
set foldlevel=99

" Performance
set lazyredraw
set updatetime=300
