#!/bin/zsh
# NICUP14's custom zsh function definitions

# Saves output to clipboard
c() {
    "$@" | xclip -selection clipboard
}

# Select from output with vim then save to clipboard
cv() {
    "$@" | vim -c 'autocmd VimLeavePre * execute "%!xclip -selection clipboard"' \
               -c 'set buftype=nowrite' \
               -c 'startinsert' -
}

# Searches for a matching PDF entry in ~/Documents
doc() {
    local file
    file=$(find -L ~/Documents -name '*.pdf' | fzf) && firefox "$file" &
}

# Searches for a matching entry in the Arch Linux wiki
adoc() {
    local file
    file=$(find /usr/share/doc/arch-wiki/html -name '*.html' | fzf) && firefox "$file"
}

# Displays stylized markdown directly inside the terminal
mdv() {
    pandoc -f gfm -t html "$@" | w3m -dump -T text/html | bat --style=grid
}

# Converts a markdown file to pdf format
mdp() {
    pandoc -f gfm -t pdf "$@" -o "${@%.md}.pdf" --include-in-header=~/.local/Listings.tex --listings
}

# Prints all information regarding a given battery
bfstat() {
    upower -i $(upower -e | grep "$@") | bat --style=grid
}

# Prints simplified information regarding a given battery
bstat() {
    upower -i $(upower -e | grep "$@") | grep -E '(state|native-path|energy-rate|time to empty|capacity|percentage):' | bat --style=grid
}

# Runs "make clean" recursively
mkrclean() {
    find "$@" -type d -exec make -C '{}' clean \;
}
