#!/bin/zsh
# NICUP14's custom zsh alias definitions

# Zsh configuration-related aliases
alias sb='source ~/.zshrc'
alias vb='vim ~/.zshrc'
alias sa='source ~/.zsh_aliases'
alias va='vim ~/.zsh_aliases'
alias sf='source ~/.zsh_functions'
alias vf='vim ~/.zsh_functions'

# Trash aliases
alias t='trash'
alias tr='trash-restore'
alias tls='trash-list'

# Arch aliases
alias cd='z'
alias d='doas'
alias q='exit'
alias sx='startx' # X11 server
alias fx='~/.fbterm' # fbterm server

# ADB
alias pmls='./adb shell pm list packages'
alias pmrm='./adb shell pm disable-user --user 0'
alias pmadd='./adb shell pm enable'

# GNU coreutils-related aliases
alias rmf='rm -f'
alias rm='rm -vi'
alias mv='mv -vi -S .bak'
alias cp='cp -vi -S .bak'
alias ccp='command cp'
alias ls='ls --color=auto --group-directories-first'
alias la='ls -A'
alias ll='ls -lh'
