#!/bin/zsh
# NICUP14's custom zsh function definitions

# Saves output to clipboard
c() {
    "$@" | xclip -selection clipboard
}

# Select from output with vim then save to clipboard
cv() {
    "$@" | vim -c 'autocmd VimLeavePre * execute "%!xclip -selection clipboard"' \
               -c 'set buftype=nowrite' \
               -c 'startinsert' -
}

# Searches for a matching PDF entry in ~/Documents
doc() {
    local file
    file=$(find ~/Documents -name '*.pdf' | fzf) && zathura "$file" &
}

# Searches for a matching entry in the Arch Linux wiki
adoc() {
    local file
    file=$(find /usr/share/doc/arch-wiki/html -name '*.html' | fzf) && firefox "$file"
}

# Searches for a local matching PDF entry in ~/Documents/Wiki
wdoc() {
    local file
    file=$(find ~/Documents/Wiki -name '*.pdf' | fzf) && zathura "$file"
}

mdv() {
    pandoc -f gfm -t html "$@" | w3m -dump -T text/html | bat
}

# Prints information regarding a given battery
bstat() {
    upower -i $(upower -e | grep "$@") | grep -E '(native-path|energy-rate|time to empty|capacity|percentage):'
}

# Runs "make clean" recursively
mkrclean() {
    find "$@" -type d -exec make -C '{}' clean \;
}
