#!/bin/zsh
# NICUP14's Zsh interactive configuration file

# Configures 'zoxide'
if (( $+commands[zoxide] )); then
    eval "$(zoxide init zsh)"
fi

# Configures the user's local bin
export LBIN_PATH="$HOME/.local/bin"
if [ -d "$LBIN_PATH" ]; then
    if [[ ! ":$PATH" == ":$LBIN_PATH" ]]; then
        export PATH="$PATH:$LBIN_PATH"
    fi
fi

# Configures the user's python bin
export PYBIN_PATH="$HOME/.local/pybin"
if [ -d "$PYBIN_PATH" ]; then
    source "$PYBIN_PATH/env/bin/activate"

    if [[ ! ":$PATH:" == ":$PYBIN_PATH" ]]; then
        export PATH="$PATH:$PYBIN_PATH"
    fi
fi

# Configures 'markdownlint'
export MARKDOWNLINT_CONFIG="$HOME/.markdownlint.json"

# Configures the prompt
PROMPT='[%n %F{35}%1~%f]$ '

# Sources the user-defined aliases
ZSH_ALIASES_FILE="$HOME/.zsh_aliases"
[[ -f "$ZSH_ALIASES_FILE" ]] && source "$ZSH_ALIASES_FILE"

# Sources the user-defined functions
ZSH_FUNCTIONS_FILE="$HOME/.zsh_functions"
[[ -f "$ZSH_FUNCTIONS_FILE" ]] && source "$ZSH_FUNCTIONS_FILE"

# Enables completions
autoload -Uz compinit
compinit

# Sets zsh options
bindkey -v
# setopt CORRECT
setopt APPEND_HISTORY
setopt EXTENDED_GLOB
bindkey '^L' clear-screen
zstyle ':completion:*' menu select
